name: Publish to NPM

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Bundle Package
        working-directory: ./web-wrapper
        run: |
          yarn install --frozen-lockfile
          yarn run build
      - name: Publish to NPM Registry
        working-directory: ./web-wrapper
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
