name: Create Version Tag

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.TAGGER_PAT }}

jobs:
  get-next-tag:
    name: Get Next Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.0
      - name: Extract Module Version
        id: get-tag
        run: echo "tag=v$(jq -r .version deno.jsonc)" >> $GITHUB_OUTPUT

  get-last-tag:
    name: Get Last Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Latest Tag Name
        id: get-tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
            semver_only: true

  create-tag:
    if: needs.get-next-tag.outputs.tag != needs.get-last-tag.outputs.tag
    name: Create Tag
    runs-on: ubuntu-latest
    needs:
      - get-next-tag
      - get-last-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Tag
        run: |
          git config user.name "Fergus Bentley"
          git config user.email "fergusbentley@gmail.com"
          git tag ${{ needs.get-next-tag.outputs.tag }}
          git push origin ${{ needs.get-next-tag.outputs.tag }}
